import Header from '@/pages/Header'
import './globals.css'
import { ReactNode } from 'react'
import Footer from '@/pages/Footer'
import Whatsapp from '@/Components/Whatsapp'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      {/* eslint-disable-next-line react/no-unknown-property */}
      <body cz-shortcut-listen="true">
        <Header />
        {children}
        <Footer />
        <Whatsapp />
      </body>
    </html>
  )
}
